/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BaiTapLon.Views.ChuTro;

import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.YES_OPTION;

import BaiTapLon.Controllers.NguoiDungController;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.apache.poi.ss.usermodel.BorderStyle;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.CreationHelper;
import org.apache.poi.ss.usermodel.FillPatternType;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.ss.usermodel.VerticalAlignment;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author ADMIN
 */
public class frmQuanLyNguoiDung extends javax.swing.JFrame {

    private static DefaultTableModel model;
    private static List<BaiTapLon.Model.NguoiDungModel> arrNguoiDung = new ArrayList<>();
    private String macu, timKiem;
    private boolean ktThem;
    private FileOutputStream out;
    DecimalFormat formatter = new DecimalFormat("###,###,###");
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    LocalDateTime currentDateTime = LocalDateTime.now();
    DateTimeFormatter formatterTime = DateTimeFormatter.ofPattern(
            "yyyy-MM-dd HH:mm:ss"
    );
    String formattedDateTime = currentDateTime.format(formatterTime);
    private static String hoten, sđt, email, diachi, matkhau, phanquyen;

    /**
     * Creates new form frmQuanLyNguoiDung
     */
    public frmQuanLyNguoiDung() {
        initComponents();
        initTable();
        KhoaMo(false);
        LayNguon();
    }

    public void initTable() {
        model = (DefaultTableModel) tblNguoiDung.getModel();
        String[] columns = {
            "Mã Người Dùng",
            "Họ tên",
            "Số Điện Thoại",
            "Email",
            "Địa chỉ",
            "Mật khẩu",
            "Phân quyền",};
        model.setColumnIdentifiers(columns);
    }

    public void XoaTrang() {
        txtHoTen.setText("");
        txtSĐT.setText("");
        txtEmail.setText("");
        txtDiaChi.setText("");
        txtMatKhau.setText("");
        txtMatKhau.setEnabled(true);
        //        btnGRole.clearSelection();
        lblMaNguoiDung.setText("XX");
    }

    public void KhoaMo(boolean b) {
        txtHoTen.setEditable(b);
        txtSĐT.setEditable(b);
        txtMatKhau.setEditable(b);
        txtEmail.setEditable(b);
        txtDiaChi.setEditable(b);
        rbNguoiDung.setEnabled(b);
        rbNguoiThueTro.setEnabled(b);

        tblNguoiDung.setEnabled(!b);
        btnThem.setEnabled(!b);
        btnXoa.setEnabled(!b);
        btnSua.setEnabled(!b);
        btnReset.setEnabled(!b);
        btnThungRac.setEnabled(!b);
        btnExport.setEnabled(!b);

        btnLuu.setEnabled(b);
        btnHuy.setEnabled(b);
    }

    public void LayNguon() {
        arrNguoiDung = BaiTapLon.Controllers.NguoiDungController.LayNguonNguoiDung();
        //        System.out.println("data" + arrNguoiDung);
        model.setRowCount(0);
        arrNguoiDung.forEach(NguoiDung -> {
            model.addRow(
                    new Object[]{
                        NguoiDung.getId(),
                        NguoiDung.getHoTen(),
                        NguoiDung.getDienThoai(),
                        NguoiDung.getEmail(),
                        NguoiDung.getDiaChi(),
                        NguoiDung.getMatKhau(),
                        NguoiDung.getRole(),}
            );
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    btnRole = new javax.swing.ButtonGroup();
    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    txtTimKiem = new javax.swing.JTextField();
    btnTimKiem = new javax.swing.JButton();
    jPanel3 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    lblMaNguoiDung = new javax.swing.JLabel();
    txtHoTen = new javax.swing.JTextField();
    txtSĐT = new javax.swing.JTextField();
    txtEmail = new javax.swing.JTextField();
    txtDiaChi = new javax.swing.JTextField();
    txtMatKhau = new javax.swing.JTextField();
    rbNguoiDung = new javax.swing.JRadioButton();
    rbNguoiThueTro = new javax.swing.JRadioButton();
    jPanel4 = new javax.swing.JPanel();
    btnThem = new javax.swing.JButton();
    btnSua = new javax.swing.JButton();
    btnThungRac = new javax.swing.JButton();
    btnReset = new javax.swing.JButton();
    btnExport = new javax.swing.JButton();
    btnXoa = new javax.swing.JButton();
    btnLuu = new javax.swing.JButton();
    btnHuy = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    tblNguoiDung = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("QUẢN LÝ NGƯỜI DÙNG");

    jPanel1.setBackground(new java.awt.Color(40, 46, 62));

    jPanel2.setBackground(new java.awt.Color(46, 56, 86));
    jPanel2.setBorder(
      javax.swing.BorderFactory.createTitledBorder(
        javax.swing.BorderFactory.createLineBorder(
          new java.awt.Color(255, 205, 31),
          2
        ),
        "Tìm Kiếm",
        javax.swing.border.TitledBorder.CENTER,
        javax.swing.border.TitledBorder.TOP,
        new java.awt.Font("Segoe UI", 1, 14),
        new java.awt.Color(255, 205, 31)
      )
    ); // NOI18N

    txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    txtTimKiem.setForeground(new java.awt.Color(40, 46, 62));
    txtTimKiem.addFocusListener(
      new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
          txtTimKiemFocusGained(evt);
        }

        public void focusLost(java.awt.event.FocusEvent evt) {
          txtTimKiemFocusLost(evt);
        }
      }
    );

    btnTimKiem.setBackground(new java.awt.Color(255, 205, 31));
    btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnTimKiem.setForeground(new java.awt.Color(40, 46, 62));
    btnTimKiem.setIcon(
      new javax.swing.ImageIcon(
        getClass().getResource("/BaiTapLon/Icon/magnifier.png")
      )
    ); // NOI18N
    btnTimKiem.setText("Tìm Kiếm");
    btnTimKiem.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          btnTimKiemActionPerformed(evt);
        }
      }
    );

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
      jPanel2
    );
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel2Layout
            .createSequentialGroup()
            .addGap(61, 61, 61)
            .addComponent(
              txtTimKiem,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              698,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.RELATED,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
            .addComponent(
              btnTimKiem,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              214,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(55, 55, 55)
        )
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel2Layout
            .createSequentialGroup()
            .addGap(15, 15, 15)
            .addGroup(
              jPanel2Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(
                  txtTimKiem,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  39,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(
                  btnTimKiem,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
            )
            .addContainerGap(15, Short.MAX_VALUE)
        )
    );

    jPanel3.setBackground(new java.awt.Color(207, 243, 243));

    jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(40, 46, 62));
    jLabel1.setText("QUẢN LÝ NGƯỜI DÙNG");

    jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(40, 46, 62));
    jLabel2.setText("Họ tên");

    jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(40, 46, 62));
    jLabel3.setText("Số điện thoại");

    jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(40, 46, 62));
    jLabel4.setText("Email");

    jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(40, 46, 62));
    jLabel5.setText("Địa chỉ");

    jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(40, 46, 62));
    jLabel6.setText("Mật khẩu");

    jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(40, 46, 62));
    jLabel7.setText("Phân quyền");

    jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(40, 46, 62));
    jLabel8.setText("Mã người dùng");

    lblMaNguoiDung.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    lblMaNguoiDung.setForeground(new java.awt.Color(255, 205, 31));
    lblMaNguoiDung.setText("XX");

    btnRole.add(rbNguoiDung);
    rbNguoiDung.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
    rbNguoiDung.setForeground(new java.awt.Color(40, 46, 62));
    rbNguoiDung.setText("Người dùng");

    btnRole.add(rbNguoiThueTro);
    rbNguoiThueTro.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
    rbNguoiThueTro.setForeground(new java.awt.Color(40, 46, 62));
    rbNguoiThueTro.setText("Người thuê trọ");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
      jPanel3
    );
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel3Layout
            .createSequentialGroup()
            .addGap(28, 28, 28)
            .addGroup(
              jPanel3Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  jPanel3Layout
                    .createSequentialGroup()
                    .addComponent(jLabel1)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      Short.MAX_VALUE
                    )
                    .addComponent(jLabel8)
                    .addGap(69, 69, 69)
                    .addComponent(lblMaNguoiDung)
                )
                .addGroup(
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  jPanel3Layout
                    .createSequentialGroup()
                    .addGroup(
                      jPanel3Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                    )
                    .addGroup(
                      jPanel3Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addGroup(
                          jPanel3Layout
                            .createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(rbNguoiDung)
                            .addGap(78, 78, 78)
                            .addComponent(rbNguoiThueTro)
                            .addGap(0, 226, Short.MAX_VALUE)
                        )
                        .addGroup(
                          jPanel3Layout
                            .createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(txtMatKhau)
                        )
                    )
                )
                .addGroup(
                  jPanel3Layout
                    .createSequentialGroup()
                    .addGroup(
                      jPanel3Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                    )
                    .addGap(34, 34, 34)
                    .addGroup(
                      jPanel3Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addComponent(txtDiaChi)
                        .addComponent(txtEmail)
                        .addComponent(txtHoTen)
                        .addComponent(txtSĐT)
                    )
                )
            )
            .addGap(16, 16, 16)
        )
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel3Layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              jPanel3Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(jLabel8)
                .addComponent(lblMaNguoiDung)
            )
            .addGap(18, 18, 18)
            .addGroup(
              jPanel3Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2)
                .addComponent(
                  txtHoTen,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(18, 18, 18)
            .addGroup(
              jPanel3Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel3)
                .addComponent(
                  txtSĐT,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(18, 18, 18)
            .addGroup(
              jPanel3Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel4)
                .addComponent(
                  txtEmail,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(16, 16, 16)
            .addGroup(
              jPanel3Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(
                  txtDiaChi,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(18, 18, 18)
            .addGroup(
              jPanel3Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel6)
                .addComponent(
                  txtMatKhau,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(18, 18, 18)
            .addGroup(
              jPanel3Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel7)
                .addComponent(rbNguoiDung)
                .addComponent(rbNguoiThueTro)
            )
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
        )
    );

    jPanel4.setBackground(new java.awt.Color(46, 56, 86));

    btnThem.setBackground(new java.awt.Color(255, 205, 31));
    btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnThem.setForeground(new java.awt.Color(40, 46, 62));
    btnThem.setIcon(
      new javax.swing.ImageIcon(
        getClass().getResource("/BaiTapLon/Icon/add.png")
      )
    ); // NOI18N
    btnThem.setText("Thêm");
    btnThem.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          btnThemActionPerformed(evt);
        }
      }
    );

    btnSua.setBackground(new java.awt.Color(255, 205, 31));
    btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnSua.setForeground(new java.awt.Color(40, 46, 62));
    btnSua.setIcon(
      new javax.swing.ImageIcon(
        getClass().getResource("/BaiTapLon/Icon/edit.png")
      )
    ); // NOI18N
    btnSua.setText("Sửa");
    btnSua.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          btnSuaActionPerformed(evt);
        }
      }
    );

    btnThungRac.setBackground(new java.awt.Color(255, 205, 31));
    btnThungRac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnThungRac.setForeground(new java.awt.Color(40, 46, 62));
    btnThungRac.setIcon(
      new javax.swing.ImageIcon(
        getClass().getResource("/BaiTapLon/Icon/delete.png")
      )
    ); // NOI18N
    btnThungRac.setText("Thùng rác");
    btnThungRac.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          btnThungRacActionPerformed(evt);
        }
      }
    );

    btnReset.setBackground(new java.awt.Color(255, 205, 31));
    btnReset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnReset.setForeground(new java.awt.Color(40, 46, 62));
    btnReset.setIcon(
      new javax.swing.ImageIcon(
        getClass().getResource("/BaiTapLon/Icon/return.png")
      )
    ); // NOI18N
    btnReset.setText("Reset");
    btnReset.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          btnResetActionPerformed(evt);
        }
      }
    );

    btnExport.setBackground(new java.awt.Color(255, 205, 31));
    btnExport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnExport.setForeground(new java.awt.Color(40, 46, 62));
    btnExport.setIcon(
      new javax.swing.ImageIcon(
        getClass().getResource("/BaiTapLon/Icon/print.png")
      )
    ); // NOI18N
    btnExport.setText("In");
    btnExport.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          btnExportActionPerformed(evt);
        }
      }
    );

    btnXoa.setBackground(new java.awt.Color(255, 205, 31));
    btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnXoa.setForeground(new java.awt.Color(40, 46, 62));
    btnXoa.setIcon(
      new javax.swing.ImageIcon(
        getClass().getResource("/BaiTapLon/Icon/litter.png")
      )
    ); // NOI18N
    btnXoa.setText("Xóa");
    btnXoa.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          btnXoaActionPerformed(evt);
        }
      }
    );

    btnLuu.setBackground(new java.awt.Color(255, 205, 31));
    btnLuu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnLuu.setForeground(new java.awt.Color(40, 46, 62));
    btnLuu.setIcon(
      new javax.swing.ImageIcon(
        getClass().getResource("/BaiTapLon/Icon/diskette (1).png")
      )
    ); // NOI18N
    btnLuu.setText("Lưu");
    btnLuu.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          btnLuuActionPerformed(evt);
        }
      }
    );

    btnHuy.setBackground(new java.awt.Color(255, 205, 31));
    btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnHuy.setForeground(new java.awt.Color(40, 46, 62));
    btnHuy.setIcon(
      new javax.swing.ImageIcon(
        getClass().getResource("/BaiTapLon/Icon/cancel (1).png")
      )
    ); // NOI18N
    btnHuy.setText("Không lưu");
    btnHuy.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          btnHuyActionPerformed(evt);
        }
      }
    );

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
      jPanel4
    );
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel4Layout
            .createSequentialGroup()
            .addGap(24, 24, 24)
            .addGroup(
              jPanel4Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(
                  btnThem,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  139,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(
                  btnXoa,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  139,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(
                  btnReset,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  139,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(
                  btnLuu,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  139,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(27, 27, 27)
            .addGroup(
              jPanel4Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  jPanel4Layout
                    .createSequentialGroup()
                    .addComponent(
                      btnSua,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      139,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                    .addContainerGap(58, Short.MAX_VALUE)
                )
                .addGroup(
                  jPanel4Layout
                    .createSequentialGroup()
                    .addGroup(
                      jPanel4Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addComponent(
                          btnHuy,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          139,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addComponent(
                          btnExport,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          139,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addComponent(
                          btnThungRac,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          139,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                    )
                    .addGap(0, 0, Short.MAX_VALUE)
                )
            )
        )
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel4Layout
            .createSequentialGroup()
            .addGap(23, 23, 23)
            .addGroup(
              jPanel4Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(
                  btnThem,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  51,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(
                  btnSua,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  51,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(18, 18, 18)
            .addGroup(
              jPanel4Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(
                  btnXoa,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  51,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(
                  btnThungRac,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  51,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(18, 18, 18)
            .addGroup(
              jPanel4Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(
                  btnReset,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  51,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(
                  btnExport,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  51,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(18, 18, 18)
            .addGroup(
              jPanel4Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(
                  btnHuy,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  51,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(
                  btnLuu,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  51,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addContainerGap(37, Short.MAX_VALUE)
        )
    );

    tblNguoiDung.setBackground(new java.awt.Color(207, 243, 243));
    tblNguoiDung.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    tblNguoiDung.setForeground(new java.awt.Color(40, 46, 62));
    tblNguoiDung.setModel(
      new javax.swing.table.DefaultTableModel(
        new Object[][] {},
        new String[] {
          "Mã Người Dùng",
          "Họ tên",
          "Số ĐT",
          "Email",
          "Địa chỉ",
          "Mật khẩu",
          "Phân quyền",
        }
      ) {
        boolean[] canEdit = new boolean[] {
          false,
          false,
          false,
          false,
          false,
          false,
          false,
        };

        public boolean isCellEditable(int rowIndex, int columnIndex) {
          return canEdit[columnIndex];
        }
      }
    );
    tblNguoiDung.setSelectionBackground(new java.awt.Color(46, 56, 86));
    tblNguoiDung.setSelectionForeground(new java.awt.Color(255, 205, 31));
    tblNguoiDung.addMouseListener(
      new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
          tblNguoiDungMouseClicked(evt);
        }
      }
    );
    jScrollPane1.setViewportView(tblNguoiDung);
    if (tblNguoiDung.getColumnModel().getColumnCount() > 0) {
      tblNguoiDung.getColumnModel().getColumn(0).setResizable(false);
      tblNguoiDung.getColumnModel().getColumn(1).setResizable(false);
      tblNguoiDung.getColumnModel().getColumn(2).setResizable(false);
      tblNguoiDung.getColumnModel().getColumn(3).setResizable(false);
      tblNguoiDung.getColumnModel().getColumn(4).setResizable(false);
      tblNguoiDung.getColumnModel().getColumn(6).setResizable(false);
    }

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
      jPanel1
    );
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel1Layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              jPanel1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  jPanel1Layout
                    .createSequentialGroup()
                    .addGroup(
                      jPanel1Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addGroup(
                          jPanel1Layout
                            .createSequentialGroup()
                            .addComponent(
                              jPanel3,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              javax.swing.GroupLayout.DEFAULT_SIZE,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                            .addGap(18, 18, 18)
                            .addComponent(
                              jPanel4,
                              javax.swing.GroupLayout.DEFAULT_SIZE,
                              javax.swing.GroupLayout.DEFAULT_SIZE,
                              Short.MAX_VALUE
                            )
                        )
                        .addComponent(
                          jPanel2,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          Short.MAX_VALUE
                        )
                    )
                    .addGap(13, 13, 13)
                )
                .addGroup(
                  jPanel1Layout
                    .createSequentialGroup()
                    .addComponent(jScrollPane1)
                    .addContainerGap()
                )
            )
        )
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel1Layout
            .createSequentialGroup()
            .addContainerGap()
            .addComponent(
              jPanel2,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(18, 18, 18)
            .addGroup(
              jPanel1Layout
                .createParallelGroup(
                  javax.swing.GroupLayout.Alignment.LEADING,
                  false
                )
                .addComponent(
                  jPanel4,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
                .addComponent(
                  jPanel3,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
            )
            .addGap(18, 18, 18)
            .addComponent(
              jScrollPane1,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
        )
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(
          jPanel1,
          javax.swing.GroupLayout.DEFAULT_SIZE,
          javax.swing.GroupLayout.DEFAULT_SIZE,
          Short.MAX_VALUE
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(
          jPanel1,
          javax.swing.GroupLayout.DEFAULT_SIZE,
          javax.swing.GroupLayout.DEFAULT_SIZE,
          Short.MAX_VALUE
        )
    );

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void txtTimKiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemFocusGained
      // TODO add your handling code here:
      if (txtTimKiem
              .getText()
              .equals("Nhập mã người dùng hoặc số điện thoại để tìm kiếm người dùng!")) {
          txtTimKiem.setText("");
      }
  }//GEN-LAST:event_txtTimKiemFocusGained

  private void txtTimKiemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemFocusLost
      // TODO add your handling code here:
      if (txtTimKiem.getText().isEmpty()) {
          txtTimKiem.setText(
                  "Nhập mã người dùng hoặc số điện thoại để tìm kiếm người dùng!"
          );
      }
  }//GEN-LAST:event_txtTimKiemFocusLost

  private void btnThungRacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThungRacActionPerformed
      // TODO add your handling code here:
      frmThungRacNguoiDung frmTR = new frmThungRacNguoiDung();
      frmTR.setVisible(true);
  }//GEN-LAST:event_btnThungRacActionPerformed

  private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
      // TODO add your handling code here:
      XoaTrang();
      txtHoTen.requestFocus();
  }//GEN-LAST:event_btnResetActionPerformed

  private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
      // TODO add your handling code here:\
      ktThem = true;
      macu = "";
      KhoaMo(true);
      XoaTrang();
      txtHoTen.requestFocus();
  }//GEN-LAST:event_btnThemActionPerformed

  private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
      // TODO add your handling code here:\
      XoaTrang();
      KhoaMo(false);
  }//GEN-LAST:event_btnHuyActionPerformed

    public boolean isValidEmail(String email) {
        String emailRegex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
        Pattern pattern = Pattern.compile(emailRegex);
        return pattern.matcher(email).matches();
    }

    public boolean isValidSdt(String DienThoai) {
        String DienThoaiRegex
                = "^(0|\\+84)(\\s|\\.)?((3[2-9])|(5[689])|(7[06-9])|(8[1-689])|(9[0-46-9]))(\\d)(\\s|\\.)?(\\d{3})(\\s|\\.)?(\\d{3})$";
        Pattern pattern = Pattern.compile(DienThoaiRegex);
        return pattern.matcher(DienThoai).matches();
    }

  private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
      // TODO add your handling code here:
      hoten = txtHoTen.getText();
      sđt = txtSĐT.getText();
      email = txtEmail.getText();
      diachi = txtDiaChi.getText();
      matkhau = txtMatKhau.getText();
      if (rbNguoiDung.isSelected()) {
          phanquyen = "User";
      } else if (rbNguoiThueTro.isSelected()) {
          phanquyen = "Tenants";
      } else {
          phanquyen = "Admin";
      }
      if (!isValidEmail(email)) {
          JOptionPane.showMessageDialog(
                  this,
                  "Email không hợp lệ!",
                  "Error",
                  JOptionPane.ERROR_MESSAGE
          );
          return;
      }

      if (!isValidSdt(sđt)) {
          JOptionPane.showMessageDialog(
                  this,
                  "Sdt không hợp lệ!",
                  "Error",
                  JOptionPane.ERROR_MESSAGE
          );
          return;
      }
      BaiTapLon.Model.NguoiDungModel nguoidung = new BaiTapLon.Model.NguoiDungModel(
              hoten,
              email,
              sđt,
              diachi,
              matkhau,
              phanquyen
      );
      if (ktThem == true) {
          NguoiDungController.ThemNguoiDung(nguoidung);
      } else {
          NguoiDungController.CapNhatNguoiDung(nguoidung, macu);
      }
      LayNguon();
      KhoaMo(false);
  }//GEN-LAST:event_btnLuuActionPerformed

  private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
      String maNguoiDung = lblMaNguoiDung.getText(); // Lấy mã người dùng từ label
      // Code xử lý xóa người dùng
      if (JOptionPane.showConfirmDialog(
              null,
              "Xác nhận xóa?",
              "Xóa hóa đơn",
              ERROR_MESSAGE
      )
              == YES_OPTION) {
          NguoiDungController.XoaVaoThungRac(maNguoiDung);
          LayNguon(); // Sau khi xóa thành công, cập nhật lại dữ liệu trong bảng
      }
  }//GEN-LAST:event_btnXoaActionPerformed

  private void tblNguoiDungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNguoiDungMouseClicked
      // TODO add your handling code here:
      int index = tblNguoiDung.getSelectedRow();
      TableModel model = tblNguoiDung.getModel();
      String id = model.getValueAt(index, 0).toString();
      String hoTen = model.getValueAt(index, 1).toString();
      String email = model.getValueAt(index, 3).toString();
      String DienThoai = model.getValueAt(index, 2).toString();
      String diaChi = model.getValueAt(index, 4).toString();
      String matKhau = model.getValueAt(index, 5).toString();
      String role = model.getValueAt(index, 6).toString();
      lblMaNguoiDung.setText(id);
      txtMatKhau.setEnabled(false);
      txtHoTen.setText(hoTen);
      txtSĐT.setText(DienThoai);
      txtEmail.setText(email);
      txtDiaChi.setText(diaChi);
      txtMatKhau.setText(matKhau);
      if (role.equalsIgnoreCase("User")) {
          rbNguoiDung.setSelected(true);
      } else if (role.equalsIgnoreCase("Tenants")) {
          rbNguoiThueTro.setSelected(true);
      } else {
          btnRole.clearSelection();
      }
  }//GEN-LAST:event_tblNguoiDungMouseClicked

  private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
      // TODO add your handling code here:
      if (lblMaNguoiDung.getText().length() <= 0) {
          return;
      }
      ktThem = false;
      macu = lblMaNguoiDung.getText();
      KhoaMo(true);
      txtHoTen.requestFocus();
  }//GEN-LAST:event_btnSuaActionPerformed

    //    public static File inPDF(long id, String hoten, String sđt, String email, String diachi, String phanquyent) {
    //        File fileToSave = null;
    //        try {
    //            String fontPath = "C:\\Users\\ADMIN\\Downloads\\DA1_TroViet\\DA1_TroViet\\src\\main\\resources\\tiengviet.ttf";
    //            BaseFont bf = BaseFont.createFont(fontPath, BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
    //            Font font = new Font(bf, 14, Font.NORMAL, BaseColor.BLACK);
    //            Font fontt = new Font(bf, 12, Font.NORMAL, BaseColor.BLACK);
    //            Font font_name = new Font(bf, 24, Font.NORMAL, BaseColor.BLACK);
    //
    //            JFileChooser fileChooser = new JFileChooser();
    //            fileChooser.setDialogTitle("Xuất file PDF");
    //
    //            int returnValue = fileChooser.showSaveDialog(null);
    //            if (returnValue == JFileChooser.APPROVE_OPTION) {
    //                fileToSave = fileChooser.getSelectedFile();
    //                String fileName = fileToSave.getName();
    //                if (!fileName.endsWith(".pdf")) {
    //                    // Gắn phần mở rộng ".pdf" vào tên file nếu chưa có
    //                    fileToSave = new File(fileToSave.getAbsolutePath() + ".pdf");
    //                }
    //                Document document = new Document(PageSize.A6);
    //                PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(fileToSave));
    //                document.open();
    //
    //                Paragraph header = new Paragraph("Trọ Việt", font);
    //                Paragraph name = new Paragraph("Danh sách người dùng", font_name);
    //                Paragraph thongtin = new Paragraph("Mã hóa đơn: " + id, font);
    //
    //                PdfPTable tbl = new PdfPTable(5);
    //                float[] columnWidths = {2f, 1.5f, 2f, 3f, 1.5f}; // Độ rộng của mỗi cột
    //                tbl.setWidths(columnWidths);
    //                tbl.addCell(new Phrase("Họ tên", font));
    //                tbl.addCell(new Phrase("SĐT", font));
    //                tbl.addCell(new Phrase("Email", font));
    //                tbl.addCell(new Phrase("Địa chỉ", font));
    //                tbl.addCell(new Phrase("Phân quyền", font));
    //
    //                tbl.addCell(new Phrase(hoten, fontt));
    //                tbl.addCell(new Phrase(sđt, fontt));
    //                tbl.addCell(new Phrase(email, fontt));
    //                tbl.addCell(new Phrase(diachi, fontt));
    //                tbl.addCell(new Phrase(phanquyent, fontt));
    //
    //                header.setAlignment(Element.ALIGN_CENTER);
    //                name.setAlignment(Element.ALIGN_CENTER);
    //                name.setSpacingAfter(5);
    //                thongtin.setSpacingAfter(5);
    //
    //                int numberOfPages = writer.getPageNumber();
    //                Paragraph numberP = new Paragraph(numberOfPages + "", fontt);
    //                numberP.setAlignment(Element.ALIGN_CENTER);
    //
    //                document.add(header);
    //                document.add(name);
    //                document.add(thongtin);
    //                document.add(tbl);
    //                document.add(numberP);
    //
    //                document.close();
    //                writer.close();
    //            }
    //        } catch (DocumentException | IOException ex) {
    //            JOptionPane.showMessageDialog(null, "Lỗi: " + ex.getMessage());
    //        }
    //        return fileToSave;
    //    }
    private static CellStyle createStyleForHeader(XSSFSheet sheet) {
        // Create font
        org.apache.poi.ss.usermodel.Font font = sheet.getWorkbook().createFont();
        font.setFontName("Times New Roman");
        font.setBold(true);
        font.setFontHeightInPoints((short) 12); // font size
        font.setColor(IndexedColors.WHITE.getIndex()); // text color

        // Create CellStyle
        CellStyle cellStyle = sheet.getWorkbook().createCellStyle();
        cellStyle.setFont(font);
        cellStyle.setAlignment(HorizontalAlignment.CENTER);
        cellStyle.setVerticalAlignment(VerticalAlignment.TOP);
        cellStyle.setFillForegroundColor(IndexedColors.DARK_GREEN.getIndex());
        cellStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        cellStyle.setBorderBottom(BorderStyle.THIN);
        cellStyle.setWrapText(true);
        return cellStyle;
    }

    private void ExportExcel(ResultSet rs) {
        try {
            XSSFWorkbook workbook = new XSSFWorkbook();
            XSSFSheet spreadsheet = workbook.createSheet("NguoiDung");
            // register the columns you wish to track and compute the column width

            CreationHelper createHelper = workbook.getCreationHelper();

            XSSFRow row = null;
            Cell cell = null;

            row = spreadsheet.createRow((short) 2);
            row.setHeight((short) 500);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("DANH SÁCH NGƯỜI DÙNG");

            //Tạo dòng tiêu đều của bảng
            // create CellStyle
            CellStyle cellStyle_Head = createStyleForHeader(spreadsheet);
            row = spreadsheet.createRow((short) 3);
            row.setHeight((short) 500);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellStyle(cellStyle_Head);
            cell.setCellValue("STT");

            cell = row.createCell(1, CellType.STRING);
            cell.setCellStyle(cellStyle_Head);
            cell.setCellValue("Mã Người Dùng");

            cell = row.createCell(2, CellType.STRING);
            cell.setCellStyle(cellStyle_Head);
            cell.setCellValue("Họ Tên");

            cell = row.createCell(3, CellType.STRING);
            cell.setCellStyle(cellStyle_Head);
            cell.setCellValue("Số Điện Thoại");

            cell = row.createCell(4, CellType.STRING);
            cell.setCellStyle(cellStyle_Head);
            cell.setCellValue("Email");

            cell = row.createCell(5, CellType.STRING);
            cell.setCellStyle(cellStyle_Head);
            cell.setCellValue("Địa Chỉ");

            cell = row.createCell(6, CellType.STRING);
            cell.setCellStyle(cellStyle_Head);
            cell.setCellValue("Mật Khẩu");

            cell = row.createCell(7, CellType.STRING);
            cell.setCellStyle(cellStyle_Head);
            cell.setCellValue("Phân Quyền");

            ResultSetMetaData rsmd = rs.getMetaData();
            int tongsocot = rsmd.getColumnCount();

            //Đinh dạng Tạo đường kẻ cho ô chứa dữ liệu
            CellStyle cellStyle_data = spreadsheet.getWorkbook().createCellStyle();
            cellStyle_data.setBorderLeft(BorderStyle.THIN);
            cellStyle_data.setBorderRight(BorderStyle.THIN);
            cellStyle_data.setBorderBottom(BorderStyle.THIN);

            int i = 0;
            while (rs.next()) {
                row = spreadsheet.createRow((short) 4 + i);
                row.setHeight((short) 400);

                cell = row.createCell(0);
                cell.setCellStyle(cellStyle_data);
                cell.setCellValue(i + 1);

                cell = row.createCell(1);
                cell.setCellStyle(cellStyle_data);
                cell.setCellValue(rs.getString("Id"));

                cell = row.createCell(2);
                cell.setCellStyle(cellStyle_data);
                cell.setCellValue(rs.getString("HoTen"));

                //Định dạng ngày tháng trong excel
                //                java.util.Date ngay = new java.util.Date(rs.getDate("Ngaysinh").getTime());
                //                CellStyle cellStyle = workbook.createCellStyle();
                //                cellStyle.setDataFormat(createHelper.createDataFormat().getFormat("dd/MM/yyyy"));
                //                cellStyle.setBorderLeft(BorderStyle.THIN);
                //                cellStyle.setBorderRight(BorderStyle.THIN);
                //                cellStyle.setBorderBottom(BorderStyle.THIN);
                //                cell = row.createCell(3);
                //                cell.setCellValue(ngay);
                //                cell.setCellStyle(cellStyle);
                cell = row.createCell(3);
                cell.setCellStyle(cellStyle_data);
                cell.setCellValue(rs.getString("DienThoai"));

                cell = row.createCell(4);
                cell.setCellStyle(cellStyle_data);
                cell.setCellValue(rs.getString("Email"));

                cell = row.createCell(5);
                cell.setCellStyle(cellStyle_data);
                cell.setCellValue(rs.getString("DiaChi"));

                cell = row.createCell(6);
                cell.setCellStyle(cellStyle_data);
                cell.setCellValue(rs.getString("MatKhau"));

                cell = row.createCell(7);
                cell.setCellStyle(cellStyle_data);
                cell.setCellValue(rs.getString("VaiTro"));

                i++;
            }
            //Hiệu chỉnh độ rộng của cột
            for (int col = 0; col < tongsocot; col++) {
                spreadsheet.autoSizeColumn(col);
            }

            File f = new File("D:\\Nam3\\Ky3\\JAVASWING\\BaiTapLon\\DUOGBACH.xlsx");
            out = new FileOutputStream(f);
            workbook.write(out);
            out.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

  private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
      Connection con = null;
      PreparedStatement statement = null;
      ResultSet rs = null;
      try {
          String timkiem = txtTimKiem.getText();
          con
                  = DriverManager.getConnection(
                          "jdbc:sqlserver://localhost:1433;databaseName=BaiTapLon;user=sa;password=bachdeptrai123"
                  );
          String SQL;
          if (timkiem != null && !timkiem.isEmpty()) {
              SQL = "SELECT * FROM NguoiDung WHERE Id LIKE ? OR DienThoai LIKE ?";
              statement = con.prepareStatement(SQL);
              statement.setString(1, "%" + timkiem + "%");
              statement.setString(2, "%" + timkiem + "%");
          } else {
              SQL = "SELECT * FROM NguoiDung";
              statement = con.prepareStatement(SQL);
          }
          rs = statement.executeQuery();

          // Hiển thị dữ liệu từ ResultSet lên JTable
          ExportExcel(rs);
      } catch (Exception e) {
          e.printStackTrace();
      } finally {
          try {
              if (rs != null) {
                  rs.close();
              }
              if (statement != null) {
                  statement.close();
              }
              if (con != null) {
                  con.close();
              }
          } catch (SQLException ex) {
              ex.printStackTrace();
          }
      }
  }//GEN-LAST:event_btnExportActionPerformed

  private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
      // TODO add your handling code here:
      timKiem = txtTimKiem.getText();
      arrNguoiDung
              = BaiTapLon.Controllers.NguoiDungController.TimKiemNguoiDung(timKiem);
      //        System.out.println("data" + arrNguoiDung);
      model.setRowCount(0);
      arrNguoiDung.forEach(NguoiDung -> {
          model.addRow(
                  new Object[]{
                      NguoiDung.getId(),
                      NguoiDung.getHoTen(),
                      NguoiDung.getDienThoai(),
                      NguoiDung.getEmail(),
                      NguoiDung.getDiaChi(),
                      NguoiDung.getMatKhau(),
                      NguoiDung.getRole(),}
          );
      });
  }//GEN-LAST:event_btnTimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger
                    .getLogger(frmQuanLyNguoiDung.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger
                    .getLogger(frmQuanLyNguoiDung.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger
                    .getLogger(frmQuanLyNguoiDung.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger
                    .getLogger(frmQuanLyNguoiDung.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(
                new Runnable() {
            public void run() {
                new frmQuanLyNguoiDung().setVisible(true);
            }
        }
        );
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnExport;
  private javax.swing.JButton btnHuy;
  private javax.swing.JButton btnLuu;
  private javax.swing.JButton btnReset;
  private javax.swing.ButtonGroup btnRole;
  private javax.swing.JButton btnSua;
  private javax.swing.JButton btnThem;
  private javax.swing.JButton btnThungRac;
  private javax.swing.JButton btnTimKiem;
  private javax.swing.JButton btnXoa;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lblMaNguoiDung;
  private javax.swing.JRadioButton rbNguoiDung;
  private javax.swing.JRadioButton rbNguoiThueTro;
  private javax.swing.JTable tblNguoiDung;
  private javax.swing.JTextField txtDiaChi;
  private javax.swing.JTextField txtEmail;
  private javax.swing.JTextField txtHoTen;
  private javax.swing.JTextField txtMatKhau;
  private javax.swing.JTextField txtSĐT;
  private javax.swing.JTextField txtTimKiem;
  // End of variables declaration//GEN-END:variables
}
